In [47]:
from sklearn.preprocessing import StandardScaler,RobustScaler,MinMaxScaler
import pandas as pd
from sklearn.model_selection import train_test_split


In [48]:
df= pd.read_csv('standard_scaler_dataset.csv')

In [49]:
df.corr()

,Age,Salary,Experience
Age,1.000000,0.000555,0.049534
Salary,0.000555,1.000000,0.192420
Experience,0.049534,0.192420,1.000000


In [50]:
df.head()

,Age,Salary,Experience
0,56,32695,3
1,46,78190,7
2,32,35258,6
3,60,117538,8
4,25,69504,27


In [51]:
X = df.drop(columns=['Experience'])
y = df['Experience']

In [52]:
X

,Age,Salary
0,56,32695
1,46,78190
2,32,35258
3,60,117538
4,25,69504
...,...,...
95,24,96842
96,26,91373
97,41,36776
98,18,122787


In [53]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42,train_size=0.8)

In [54]:
xtrain

,Age,Salary
55,64,117939
88,62,56105
26,39,114651
42,35,120982
69,61,123426
...,...,...
60,57,86044
71,27,52299
14,41,82251
92,62,74262


In [55]:
scaling = StandardScaler()

Xtrain_scaled = scaling.fit_transform(xtrain)
Xtest_scaled = scaling.transform(xtest)

'''
formula => X-mean/std
fit() => it finds mean and std value

'''

'\nformula => X-mean/std\nfit() => it finds mean and std value\n\n'

In [56]:
scaling.mean_

array([4.1262500e+01, 8.9900975e+04])

In [57]:
scaling.var_

array([2.06743594e+02, 1.17311239e+09])

In [58]:
int(Xtrain_scaled[:,1].mean())

0

In [59]:
Xtrain_scaled[:,1].std()

np.float64(1.0)

In [60]:
Xtrain_scaled[:,0].std()

np.float64(1.0)

In [64]:
scaling = RobustScaler()
scaling.fit_transform(xtrain)
scaling.center_

array([4.10000e+01, 8.87085e+04])